
package com.connode.service.terminal.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NodeServices", targetNamespace = "http://ws.terminal.service.connode.com/", wsdlLocation = "https://jvvnl-tnd1.dev.cyanconnode.com/nms/ws/NodeServices?wsdl")
public class NodeServices_Service
    extends Service
{

    private final static URL NODESERVICES_WSDL_LOCATION;
    private final static WebServiceException NODESERVICES_EXCEPTION;
    private final static QName NODESERVICES_QNAME = new QName("http://ws.terminal.service.connode.com/", "NodeServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://jvvnl-tnd1.dev.cyanconnode.com/nms/ws/NodeServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NODESERVICES_WSDL_LOCATION = url;
        NODESERVICES_EXCEPTION = e;
    }

    public NodeServices_Service() {
        super(__getWsdlLocation(), NODESERVICES_QNAME);
    }

    public NodeServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NODESERVICES_QNAME, features);
    }

    public NodeServices_Service(URL wsdlLocation) {
        super(wsdlLocation, NODESERVICES_QNAME);
    }

    public NodeServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NODESERVICES_QNAME, features);
    }

    public NodeServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NodeServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NodeServices
     */
    @WebEndpoint(name = "NodeServices")
    public NodeServices getNodeServices() {
        return super.getPort(new QName("http://ws.terminal.service.connode.com/", "NodeServices"), NodeServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NodeServices
     */
    @WebEndpoint(name = "NodeServices")
    public NodeServices getNodeServices(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.terminal.service.connode.com/", "NodeServices"), NodeServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NODESERVICES_EXCEPTION!= null) {
            throw NODESERVICES_EXCEPTION;
        }
        return NODESERVICES_WSDL_LOCATION;
    }

}
