
package com.connode.service.terminal.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NodeFault", targetNamespace = "http://ws.terminal.service.connode.com/")
public class WSNodeException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WsNodeFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WSNodeException(String message, WsNodeFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WSNodeException(String message, WsNodeFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.connode.service.terminal.ws.WsNodeFault
     */
    public WsNodeFault getFaultInfo() {
        return faultInfo;
    }

}
